<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FNFBot</AssemblyName>
    <RootNamespace>FNFBot</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <Resource Include="Resources\FNFBotLogo.png"/>
    <Resource Include="Resources\FNFBotIcon.ico"/>
  </ItemGroup>
</Project>
